import { ArrowRight } from "lucide-react";

export const features = [
  {
    title: "AI-Powered Generation",
    description: "Create lesson plans in seconds using advanced AI technology.",
    icon: ArrowRight,
  },
  {
    title: "Customizable Templates",
    description:
      "Tailor lessons to your specific teaching style and requirements.",
    icon: ArrowRight,
  },
  {
    title: "Curriculum Aligned",
    description:
      "Ensure your lessons meet educational standards and objectives.",
    icon: ArrowRight,
  },
  {
    title: "Time-Saving",
    description: "Focus on teaching, not planning, with our efficient tool.",
    icon: ArrowRight,
  },
];

export const testimonials = [
  {
    name: "Sarah M.",
    role: "High School Teacher",
    quote:
      "This tool has revolutionized my lesson planning process. I save hours each week!",
  },
  {
    name: "John D.",
    role: "Elementary Educator",
    quote:
      "The AI-generated lessons are creative and engaging. My students love them!",
  },
  {
    name: "Emily R.",
    role: "Middle School Teacher",
    quote:
      "The customization options allow me to tailor lessons perfectly to my class needs.",
  },
];

export const tiers = [
  {
    name: "Free",
    price: "€0",
    features: [
      "5 lesson plans per month",
      "Pre-selected topics",
      "Basic customization",
      "Email support",
    ],
  },
  {
    name: "Pro",
    price: "€5",
    features: [
      "30 lesson plans per month",
      "Custom requirements",
      "Advanced customization",
      "Priority support",
      "Exclusive templates",
    ],
  },
];

export const topics = [
  "Mathematics",
  "Science",
  "History",
  "Literature",
  "Art",
];

export const durations = [
  "30 minutes",
  "45 minutes",
  "60 minutes",
  "90 minutes",
];

export const studentLevels = [
  "No Experience",
  "Beginner",
  "Intermediate",
  "Advanced",
  "High School",
  "Undergraduate",
  "Graduate",
  "Professional",
];

export const subtopics = {
  Mathematics: [
    "Pythagorean Theorem",
    "Quadratic Equations",
    "Trigonometric Functions",
    "Logarithms",
    "Calculus: Limits",
    "Calculus: Derivatives",
    "Calculus: Integrals",
    "Linear Algebra: Matrices",
    "Probability Theory",
    "Statistical Hypothesis Testing",
    "Number Theory: Prime Numbers",
    "Geometry: Conic Sections",
    "Complex Numbers",
    "Differential Equations",
    "Graph Theory",
  ],
  Science: [
    "Newton's Laws of Motion",
    "Thermodynamics",
    "Quantum Mechanics",
    "Cellular Respiration",
    "DNA Replication",
    "Periodic Table of Elements",
    "Chemical Bonding",
    "Plate Tectonics",
    "Evolution by Natural Selection",
    "Photosynthesis",
    "Electromagnetism",
    "Astronomy: Black Holes",
    "Climate Change",
    "Genetics: Mendelian Inheritance",
    "Atomic Structure",
  ],
  History: [
    "Ancient Egypt: Pyramids",
    "Roman Empire: Rise and Fall",
    "Medieval Europe: Feudalism",
    "Renaissance: Art and Culture",
    "American Revolution",
    "French Revolution",
    "Industrial Revolution",
    "World War I",
    "World War II",
    "Cold War",
    "Civil Rights Movement",
    "Fall of the Berlin Wall",
    "Ancient Greece: Democracy",
    "Chinese Dynasties",
    "Islamic Golden Age",
  ],
  Literature: [
    "Shakespeare: Hamlet",
    "Jane Austen: Pride and Prejudice",
    "Charles Dickens: Great Expectations",
    "F. Scott Fitzgerald: The Great Gatsby",
    "George Orwell: 1984",
    "Homer: The Odyssey",
    "Gabriel García Márquez: One Hundred Years of Solitude",
    "Virginia Woolf: Mrs Dalloway",
    "Chinua Achebe: Things Fall Apart",
    "Toni Morrison: Beloved",
    "Leo Tolstoy: War and Peace",
    "Emily Dickinson: Poetry Analysis",
    "William Wordsworth: Romantic Poetry",
    "Arthur Miller: Death of a Salesman",
    "Franz Kafka: The Metamorphosis",
  ],
  Art: [
    "Leonardo da Vinci: Mona Lisa",
    "Vincent van Gogh: Starry Night",
    "Pablo Picasso: Cubism",
    "Michelangelo: Sistine Chapel Ceiling",
    "Claude Monet: Impressionism",
    "Andy Warhol: Pop Art",
    "Georgia O'Keeffe: American Modernism",
    "Frida Kahlo: Self-Portraits",
    "Jackson Pollock: Abstract Expressionism",
    "Ancient Greek Sculpture",
    "Renaissance Architecture",
    "Japanese Ukiyo-e Prints",
    "African Masks and Sculpture",
    "Art Nouveau Movement",
    "Contemporary Installation Art",
  ],
};

export const faqItems = [
  {
    question: "How accurate are the lesson plans generated by the AI?",
    answer:
      "The accuracy of the lesson plans generated by the AI depends on the quality of the input provided. Users should provide clear and specific details about their requirements to ensure the AI can generate accurate plans. You should proofread the plan and its contents to ensure it meets your needs. This tool is meant to save you time, not take away from your expertise.",
  },
  {
    question: "Can I customize the lesson plans generated by the AI?",
    answer: "No, but this is a feature that is coming soon.",
  },
  {
    question: "What types of topics can be covered in the lesson plans?",
    answer:
      "The lesson plans generated by the AI can cover a wide range of topics, including mathematics, science, history, and literature. Users can select the topic that best fits their lesson plan and if you are a pro user, you can generate plans based on your own topics.",
  },
  {
    question: "How long does it take for the AI to generate a lesson plan?",
    answer:
      "The time it takes for the AI to generate a lesson plan depends on the complexity of the topic and the specific requirements provided by the user. Generally, it takes about 30 seconds to generate a lesson plan.",
  },
  {
    question: "Can I use the lesson plans generated by the AI in my classroom?",
    answer:
      "Yes, you can use the lesson plans generated by the AI in your classroom. However, you should always review the plans to ensure they meet the specific needs of your students and align with your teaching goals.",
  },
];
