import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

const TermsOfService = () => {
  return (
    <Card className="max-w-4xl mx-auto my-8">
      <CardHeader>
        <CardTitle className="text-2xl font-bold">Terms of Service</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        <p className="text-sm text-gray-600">Last Modified: {new Date().toLocaleDateString()}</p>

        <section>
          <h2 className="text-xl font-semibold mb-2">Liability</h2>
          <p>
            <strong>No Warranty or Guarantee:</strong> We provide this service &apos;as-is&apos; and without any warranty or guarantee. While we make every effort to ensure the functionality, security, and reliability of our site, we do not make any representations or warranties regarding the accuracy, completeness, or suitability of the information and materials found or offered on this website.
          </p>
          <p className="mt-2">
            <strong>Exclusion of Liability:</strong> In no event shall we be liable for any direct, indirect, incidental, consequential, special, or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data, or other intangible losses, resulting from the use or inability to use our services.
          </p>
          <p className="mt-2">
            <strong>User Responsibility:</strong> You acknowledge and agree that your use of this service is at your own risk. We are not responsible for any damages or issues that may arise, including but not limited to, data loss, system errors, or interruptions in service. It is your responsibility to take appropriate precautions and ensure that any services or information obtained through our site meet your specific requirements.
          </p>
          <p className="mt-2">
            <strong>Indemnification:</strong> By using this service, you agree to indemnify and hold us harmless from any claims, actions, damages, liabilities, costs, and expenses, including reasonable attorneys' fees, arising out of or in connection with your use of the service or any violation of these terms.
          </p>
          <p className="mt-2">
            It's important to review and understand these terms fully. If you do not agree with any part of these terms, your only recourse is to discontinue your use of the service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">AI-Generated Content</h2>
          <p>
            <strong>No Control Over AI Output:</strong> We utilize AI technology to generate lesson plans based on user inputs. While we strive to provide accurate and appropriate content, we have no control over the specific output of the AI-generated lesson plans. The results may vary and may not always meet your expectations.
          </p>
          <p className="mt-2">
            <strong>Prohibited Content:</strong> You agree not to use our service to generate any content that is inappropriate for educational purposes, explicit, or illegal in nature. This includes, but is not limited to, content that is sexually explicit, violent, defamatory, obscene, or infringes on intellectual property rights. Any attempt to generate such content will result in an immediate ban of your account.
          </p>
          <p className="mt-2">
            <strong>Disclaimer of Responsibility:</strong> We are not responsible for any content generated by users through our application. You acknowledge and agree that you are solely responsible for the content you generate and any consequences that may arise from its use. We disclaim any liability for any harm or damages resulting from user-generated content.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">External Links</h2>
          <p>
            Our service may contain links to external websites or services that are not owned or controlled by us. We are not responsible for the content, privacy policies, or practices of any third-party websites. You acknowledge and agree that we shall not be held liable for any damages or issues that may arise from your use of such sites.
          </p>
          <p className="mt-2">
            We are not able to verify the external links uploaded by users; therefore, it is your responsibility to open them at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Account</h2>
          <p>
            <strong>Account Management:</strong> We reserve the right to manage your account at our discretion. This includes the right to delete, suspend, or lock your account and associated data without prior notice. Such actions may be taken for reasons including, but not limited to, violation of our terms of service, suspected fraudulent activities, or any other actions that may compromise the security and integrity of our platform.
          </p>
          <p className="mt-2">
            <strong>Termination:</strong> We may terminate or suspend your account for any reason, including breach of these terms. In the event of termination, you will no longer have access to your account and any data associated with it. We are not liable for any loss or damage that may result from the termination of your account.
          </p>
          <p className="mt-2">
            <strong>Account Security:</strong> It is your responsibility to maintain the security of your account credentials. You agree not to share your login information with third parties. You are solely responsible for any activities that occur under your account.
          </p>
          <p className="mt-2">
            <strong>Account Data:</strong> You can delete your account and all the associated data we store in our system at any time by going to your account settings page and deleting your account. Just note that once your account is deleted, there is no way to recover your data.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Uptime, Security, and Privacy</h2>
          <p>
            <strong>Uptime:</strong> While we strive to maintain the availability of our services, we do not provide any service level agreement (SLA). The website&apos;s uptime may be subject to occasional interruptions, including maintenance, updates, or unforeseen technical issues. Your use of this service is at your own risk, and we do not guarantee uninterrupted access to our platform.
          </p>
          <p className="mt-2">
            <strong>Security:</strong> We implement reasonable security measures to protect the integrity of our platform. However, you acknowledge that no online service can be completely secure. We do not assume responsibility for any unauthorized access, data breaches, or other security incidents that may occur. It is your responsibility to take appropriate measures to secure your account and data.
          </p>
          <p className="mt-2">
            <strong>Privacy:</strong> Your privacy is important to us. Our privacy practices are outlined in our separate Privacy Policy, which is an integral part of these terms. By using our services, you agree to the collection, use, and disclosure of your information as described in the Privacy Policy. It is your responsibility to review the Privacy Policy and understand how your data is handled.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Copyright and Content Ownership</h2>
          <p>
            <strong>Ownership of Generated Content:</strong> We do not claim any rights to the lesson plans generated using our service. We also do not claim the right to any of the user-generated data, including but not limited to, group info, posts, events, or replies, etc.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Features and Bugs</h2>
          <p>
            <strong>Continuous Improvement:</strong> We are dedicated to continuously adding new features and improving existing functionalities to enhance your experience. By agreeing to our terms, you acknowledge that the system may undergo changes over time to introduce new features or enhance existing ones.
          </p>
          <p className="mt-2">
            <strong>Bug Fixes:</strong> Bugs are an inevitable part of any software system. While we strive to maintain a seamless experience, you understand that bugs may be identified and fixed during the course of our ongoing development efforts. We appreciate your understanding and cooperation in reporting any issues you may encounter.
          </p>
          <p className="mt-2">
            <strong>Impact on User Experience:</strong> Changes to the system, including the introduction of new features or bug fixes, may impact your overall experience. By agreeing to our terms, you accept that such changes are inherent in the nature of software development, and we cannot guarantee that your experience will remain unchanged.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Use of Third Party Services</h2>
          <p>
            <strong>Third-Party Services:</strong> We utilize third-party services for hosting the application and storing user-generated lesson plans, and we are not responsible for their operations, performance, or any consequences arising from their use.
          </p>
          <p className="mt-2">
            <strong>No Affiliation:</strong> We want to make it explicitly clear that we are not affiliated with the third-party services we employ. Any issues or concerns related to their services should be directed to the respective third-party providers.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">Updates to Terms of Service</h2>
          <p>
            <strong>Right to Update:</strong> We reserve the right to update these terms of service at any time. Updates may be made to reflect changes in our services, legal requirements, or other considerations. Your continued use of our application after any such changes constitutes your acceptance of the modified terms.
          </p>
          <p className="mt-2">
            <strong>No Obligation to Notify:</strong> While we may make efforts to communicate significant changes, you agree that we are not obligated to notify users individually when updates occur. It is your responsibility to check back on these terms periodically to stay informed about any modifications.
          </p>
          <p className="mt-2">
            <strong>Review of Terms:</strong> It's advisable to review these terms regularly to ensure that you are aware of any changes that may affect your use of the application. Your continued use of the service after updates indicates your agreement to be bound by the modified terms.
          </p>
        </section>

        <p className="text-sm text-gray-600 mt-6">
          &copy; {new Date().getFullYear()} Generate Lesson Plans. All rights reserved.
        </p>
        <p className="text-sm text-gray-600">
          Contact: <a href="mailto:hello@alfiewebdev.com" className="text-blue-600 hover:underline">hello@alfiewebdev.com</a>
        </p>
      </CardContent>
    </Card>
  );
};

export default TermsOfService;
